// code generated by pbf v4.0.1

export function writeTile(obj, pbf) {
    if (obj.layers) for (const item of obj.layers) pbf.writeMessage(3, writeTileLayer, item);
}

export const TileGeomType = {
    "UNKNOWN": 0,
    "POINT": 1,
    "LINESTRING": 2,
    "POLYGON": 3
};

export function writeTileValue(obj, pbf) {
    if (obj.string_value) pbf.writeStringField(1, obj.string_value);
    if (obj.float_value) pbf.writeFloatField(2, obj.float_value);
    if (obj.double_value) pbf.writeDoubleField(3, obj.double_value);
    if (obj.int_value) pbf.writeVarintField(4, obj.int_value);
    if (obj.uint_value) pbf.writeVarintField(5, obj.uint_value);
    if (obj.sint_value) pbf.writeSVarintField(6, obj.sint_value);
    if (obj.bool_value) pbf.writeBooleanField(7, obj.bool_value);
}

export function writeTileFeature(obj, pbf) {
    if (obj.id) pbf.writeVarintField(1, obj.id);
    if (obj.tags) pbf.writePackedVarint(2, obj.tags);
    if (obj.type) pbf.writeVarintField(3, obj.type);
    if (obj.geometry) pbf.writePackedVarint(4, obj.geometry);
}

export function writeTileLayer(obj, pbf) {
    if (obj.version) pbf.writeVarintField(15, obj.version);
    if (obj.name) pbf.writeStringField(1, obj.name);
    if (obj.features) for (const item of obj.features) pbf.writeMessage(2, writeTileFeature, item);
    if (obj.keys) for (const item of obj.keys) pbf.writeStringField(3, item);
    if (obj.values) for (const item of obj.values) pbf.writeMessage(4, writeTileValue, item);
    if (obj.extent) pbf.writeVarintField(5, obj.extent);
}
